// source: models.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.models.Brain');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.models.Neuron');

goog.forwardDeclare('proto.models.Activation');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.models.Brain = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.models.Brain.repeatedFields_, null);
};
goog.inherits(proto.models.Brain, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.models.Brain.displayName = 'proto.models.Brain';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.models.Brain.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.models.Brain.prototype.toObject = function(opt_includeInstance) {
  return proto.models.Brain.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.models.Brain} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.models.Brain.toObject = function(includeInstance, msg) {
  var f, obj = {
    activation: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    hiddenList: jspb.Message.toObjectList(msg.getHiddenList(),
    proto.models.Neuron.toObject, includeInstance),
    outputList: jspb.Message.toObjectList(msg.getOutputList(),
    proto.models.Neuron.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.models.Brain}
 */
proto.models.Brain.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.models.Brain;
  return proto.models.Brain.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.models.Brain} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.models.Brain}
 */
proto.models.Brain.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.models.Activation} */ (reader.readEnum());
      msg.setActivation(value);
      break;
    case 2:
      var value = new proto.models.Neuron;
      reader.readMessage(value,proto.models.Neuron.deserializeBinaryFromReader);
      msg.addHidden(value);
      break;
    case 3:
      var value = new proto.models.Neuron;
      reader.readMessage(value,proto.models.Neuron.deserializeBinaryFromReader);
      msg.addOutput(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.models.Brain.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.models.Brain.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.models.Brain} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.models.Brain.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.models.Activation} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getHiddenList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.models.Neuron.serializeBinaryToWriter
    );
  }
  f = message.getOutputList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.models.Neuron.serializeBinaryToWriter
    );
  }
};


/**
 * required Activation activation = 1;
 * @return {!proto.models.Activation}
 */
proto.models.Brain.prototype.getActivation = function() {
  return /** @type {!proto.models.Activation} */ (jspb.Message.getFieldWithDefault(this, 1, 1));
};


/**
 * @param {!proto.models.Activation} value
 * @return {!proto.models.Brain} returns this
 */
proto.models.Brain.prototype.setActivation = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Brain} returns this
 */
proto.models.Brain.prototype.clearActivation = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Brain.prototype.hasActivation = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Neuron hidden = 2;
 * @return {!Array<!proto.models.Neuron>}
 */
proto.models.Brain.prototype.getHiddenList = function() {
  return /** @type{!Array<!proto.models.Neuron>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.models.Neuron, 2));
};


/**
 * @param {!Array<!proto.models.Neuron>} value
 * @return {!proto.models.Brain} returns this
*/
proto.models.Brain.prototype.setHiddenList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.models.Neuron=} opt_value
 * @param {number=} opt_index
 * @return {!proto.models.Neuron}
 */
proto.models.Brain.prototype.addHidden = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.models.Neuron, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.models.Brain} returns this
 */
proto.models.Brain.prototype.clearHiddenList = function() {
  return this.setHiddenList([]);
};


/**
 * repeated Neuron output = 3;
 * @return {!Array<!proto.models.Neuron>}
 */
proto.models.Brain.prototype.getOutputList = function() {
  return /** @type{!Array<!proto.models.Neuron>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.models.Neuron, 3));
};


/**
 * @param {!Array<!proto.models.Neuron>} value
 * @return {!proto.models.Brain} returns this
*/
proto.models.Brain.prototype.setOutputList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.models.Neuron=} opt_value
 * @param {number=} opt_index
 * @return {!proto.models.Neuron}
 */
proto.models.Brain.prototype.addOutput = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.models.Neuron, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.models.Brain} returns this
 */
proto.models.Brain.prototype.clearOutputList = function() {
  return this.setOutputList([]);
};


