// source: models.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.models.Constants');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.models.Constants = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.models.Constants, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.models.Constants.displayName = 'proto.models.Constants';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.models.Constants.prototype.toObject = function(opt_includeInstance) {
  return proto.models.Constants.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.models.Constants} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.models.Constants.toObject = function(includeInstance, msg) {
  var f, obj = {
    maxCycles: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    maxSteps: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    creatureAmount: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    brainSize: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    inputSize: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
    outputSize: (f = jspb.Message.getField(msg, 6)) == null ? undefined : f,
    blockAmount: (f = jspb.Message.getField(msg, 7)) == null ? undefined : f,
    blockSize: (f = jspb.Message.getOptionalFloatingPointField(msg, 8)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.models.Constants}
 */
proto.models.Constants.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.models.Constants;
  return proto.models.Constants.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.models.Constants} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.models.Constants}
 */
proto.models.Constants.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMaxCycles(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMaxSteps(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCreatureAmount(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setBrainSize(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setInputSize(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOutputSize(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setBlockAmount(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setBlockSize(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.models.Constants.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.models.Constants.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.models.Constants} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.models.Constants.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeUint32(
      7,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeFloat(
      8,
      f
    );
  }
};


/**
 * required uint32 max_cycles = 1;
 * @return {number}
 */
proto.models.Constants.prototype.getMaxCycles = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.models.Constants} returns this
 */
proto.models.Constants.prototype.setMaxCycles = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Constants} returns this
 */
proto.models.Constants.prototype.clearMaxCycles = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Constants.prototype.hasMaxCycles = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required uint32 max_steps = 2;
 * @return {number}
 */
proto.models.Constants.prototype.getMaxSteps = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.models.Constants} returns this
 */
proto.models.Constants.prototype.setMaxSteps = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Constants} returns this
 */
proto.models.Constants.prototype.clearMaxSteps = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Constants.prototype.hasMaxSteps = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required uint32 creature_amount = 3;
 * @return {number}
 */
proto.models.Constants.prototype.getCreatureAmount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.models.Constants} returns this
 */
proto.models.Constants.prototype.setCreatureAmount = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Constants} returns this
 */
proto.models.Constants.prototype.clearCreatureAmount = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Constants.prototype.hasCreatureAmount = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * required uint32 brain_size = 4;
 * @return {number}
 */
proto.models.Constants.prototype.getBrainSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.models.Constants} returns this
 */
proto.models.Constants.prototype.setBrainSize = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Constants} returns this
 */
proto.models.Constants.prototype.clearBrainSize = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Constants.prototype.hasBrainSize = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * required uint32 input_size = 5;
 * @return {number}
 */
proto.models.Constants.prototype.getInputSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.models.Constants} returns this
 */
proto.models.Constants.prototype.setInputSize = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Constants} returns this
 */
proto.models.Constants.prototype.clearInputSize = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Constants.prototype.hasInputSize = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * required uint32 output_size = 6;
 * @return {number}
 */
proto.models.Constants.prototype.getOutputSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.models.Constants} returns this
 */
proto.models.Constants.prototype.setOutputSize = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Constants} returns this
 */
proto.models.Constants.prototype.clearOutputSize = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Constants.prototype.hasOutputSize = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * required uint32 block_amount = 7;
 * @return {number}
 */
proto.models.Constants.prototype.getBlockAmount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.models.Constants} returns this
 */
proto.models.Constants.prototype.setBlockAmount = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Constants} returns this
 */
proto.models.Constants.prototype.clearBlockAmount = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Constants.prototype.hasBlockAmount = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * required float block_size = 8;
 * @return {number}
 */
proto.models.Constants.prototype.getBlockSize = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.models.Constants} returns this
 */
proto.models.Constants.prototype.setBlockSize = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Constants} returns this
 */
proto.models.Constants.prototype.clearBlockSize = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Constants.prototype.hasBlockSize = function() {
  return jspb.Message.getField(this, 8) != null;
};


