// source: models.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.models.CreatureState');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.models.Point');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.models.CreatureState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.models.CreatureState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.models.CreatureState.displayName = 'proto.models.CreatureState';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.models.CreatureState.prototype.toObject = function(opt_includeInstance) {
  return proto.models.CreatureState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.models.CreatureState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.models.CreatureState.toObject = function(includeInstance, msg) {
  var f, obj = {
    creatureId: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    translation: (f = msg.getTranslation()) && proto.models.Point.toObject(includeInstance, f),
    rotation: (f = jspb.Message.getOptionalFloatingPointField(msg, 3)) == null ? undefined : f,
    stamina: (f = jspb.Message.getOptionalFloatingPointField(msg, 4)) == null ? undefined : f,
    decision: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.models.CreatureState}
 */
proto.models.CreatureState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.models.CreatureState;
  return proto.models.CreatureState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.models.CreatureState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.models.CreatureState}
 */
proto.models.CreatureState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCreatureId(value);
      break;
    case 2:
      var value = new proto.models.Point;
      reader.readMessage(value,proto.models.Point.deserializeBinaryFromReader);
      msg.setTranslation(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setRotation(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setStamina(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDecision(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.models.CreatureState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.models.CreatureState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.models.CreatureState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.models.CreatureState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getTranslation();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.models.Point.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeUint32(
      5,
      f
    );
  }
};


/**
 * required uint32 creature_id = 1;
 * @return {number}
 */
proto.models.CreatureState.prototype.getCreatureId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.models.CreatureState} returns this
 */
proto.models.CreatureState.prototype.setCreatureId = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.CreatureState} returns this
 */
proto.models.CreatureState.prototype.clearCreatureId = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.CreatureState.prototype.hasCreatureId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required Point translation = 2;
 * @return {!proto.models.Point}
 */
proto.models.CreatureState.prototype.getTranslation = function() {
  return /** @type{!proto.models.Point} */ (
    jspb.Message.getWrapperField(this, proto.models.Point, 2, 1));
};


/**
 * @param {!proto.models.Point} value
 * @return {!proto.models.CreatureState} returns this
*/
proto.models.CreatureState.prototype.setTranslation = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.CreatureState} returns this
 */
proto.models.CreatureState.prototype.clearTranslation = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.CreatureState.prototype.hasTranslation = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required float rotation = 3;
 * @return {number}
 */
proto.models.CreatureState.prototype.getRotation = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.models.CreatureState} returns this
 */
proto.models.CreatureState.prototype.setRotation = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.CreatureState} returns this
 */
proto.models.CreatureState.prototype.clearRotation = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.CreatureState.prototype.hasRotation = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * required float stamina = 4;
 * @return {number}
 */
proto.models.CreatureState.prototype.getStamina = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.models.CreatureState} returns this
 */
proto.models.CreatureState.prototype.setStamina = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.CreatureState} returns this
 */
proto.models.CreatureState.prototype.clearStamina = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.CreatureState.prototype.hasStamina = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * required uint32 decision = 5;
 * @return {number}
 */
proto.models.CreatureState.prototype.getDecision = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.models.CreatureState} returns this
 */
proto.models.CreatureState.prototype.setDecision = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.CreatureState} returns this
 */
proto.models.CreatureState.prototype.clearDecision = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.CreatureState.prototype.hasDecision = function() {
  return jspb.Message.getField(this, 5) != null;
};


