// source: models.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.models.Creature');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.models.Bounds');
goog.require('proto.models.Brain');
goog.require('proto.models.Traits');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.models.Creature = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.models.Creature, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.models.Creature.displayName = 'proto.models.Creature';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.models.Creature.prototype.toObject = function(opt_includeInstance) {
  return proto.models.Creature.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.models.Creature} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.models.Creature.toObject = function(includeInstance, msg) {
  var f, obj = {
    creatureId: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    brain: (f = msg.getBrain()) && proto.models.Brain.toObject(includeInstance, f),
    traits: (f = msg.getTraits()) && proto.models.Traits.toObject(includeInstance, f),
    bounds: (f = msg.getBounds()) && proto.models.Bounds.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.models.Creature}
 */
proto.models.Creature.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.models.Creature;
  return proto.models.Creature.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.models.Creature} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.models.Creature}
 */
proto.models.Creature.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCreatureId(value);
      break;
    case 2:
      var value = new proto.models.Brain;
      reader.readMessage(value,proto.models.Brain.deserializeBinaryFromReader);
      msg.setBrain(value);
      break;
    case 3:
      var value = new proto.models.Traits;
      reader.readMessage(value,proto.models.Traits.deserializeBinaryFromReader);
      msg.setTraits(value);
      break;
    case 4:
      var value = new proto.models.Bounds;
      reader.readMessage(value,proto.models.Bounds.deserializeBinaryFromReader);
      msg.setBounds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.models.Creature.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.models.Creature.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.models.Creature} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.models.Creature.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getBrain();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.models.Brain.serializeBinaryToWriter
    );
  }
  f = message.getTraits();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.models.Traits.serializeBinaryToWriter
    );
  }
  f = message.getBounds();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.models.Bounds.serializeBinaryToWriter
    );
  }
};


/**
 * required uint32 creature_id = 1;
 * @return {number}
 */
proto.models.Creature.prototype.getCreatureId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.models.Creature} returns this
 */
proto.models.Creature.prototype.setCreatureId = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Creature} returns this
 */
proto.models.Creature.prototype.clearCreatureId = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Creature.prototype.hasCreatureId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required Brain brain = 2;
 * @return {!proto.models.Brain}
 */
proto.models.Creature.prototype.getBrain = function() {
  return /** @type{!proto.models.Brain} */ (
    jspb.Message.getWrapperField(this, proto.models.Brain, 2, 1));
};


/**
 * @param {!proto.models.Brain} value
 * @return {!proto.models.Creature} returns this
*/
proto.models.Creature.prototype.setBrain = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Creature} returns this
 */
proto.models.Creature.prototype.clearBrain = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Creature.prototype.hasBrain = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required Traits traits = 3;
 * @return {!proto.models.Traits}
 */
proto.models.Creature.prototype.getTraits = function() {
  return /** @type{!proto.models.Traits} */ (
    jspb.Message.getWrapperField(this, proto.models.Traits, 3, 1));
};


/**
 * @param {!proto.models.Traits} value
 * @return {!proto.models.Creature} returns this
*/
proto.models.Creature.prototype.setTraits = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Creature} returns this
 */
proto.models.Creature.prototype.clearTraits = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Creature.prototype.hasTraits = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * required Bounds bounds = 4;
 * @return {!proto.models.Bounds}
 */
proto.models.Creature.prototype.getBounds = function() {
  return /** @type{!proto.models.Bounds} */ (
    jspb.Message.getWrapperField(this, proto.models.Bounds, 4, 1));
};


/**
 * @param {!proto.models.Bounds} value
 * @return {!proto.models.Creature} returns this
*/
proto.models.Creature.prototype.setBounds = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Creature} returns this
 */
proto.models.Creature.prototype.clearBounds = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Creature.prototype.hasBounds = function() {
  return jspb.Message.getField(this, 4) != null;
};


