// source: models.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.models.Cycle');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Map');
goog.require('jspb.Message');
goog.require('proto.models.Creature');
goog.require('proto.models.Step');
goog.require('proto.models.Wall');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.models.Cycle = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.models.Cycle.repeatedFields_, null);
};
goog.inherits(proto.models.Cycle, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.models.Cycle.displayName = 'proto.models.Cycle';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.models.Cycle.repeatedFields_ = [3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.models.Cycle.prototype.toObject = function(opt_includeInstance) {
  return proto.models.Cycle.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.models.Cycle} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.models.Cycle.toObject = function(includeInstance, msg) {
  var f, obj = {
    cycleId: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    creaturesMap: (f = msg.getCreaturesMap()) ? f.toObject(includeInstance, proto.models.Creature.toObject) : [],
    wallsList: jspb.Message.toObjectList(msg.getWallsList(),
    proto.models.Wall.toObject, includeInstance),
    stepsList: jspb.Message.toObjectList(msg.getStepsList(),
    proto.models.Step.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.models.Cycle}
 */
proto.models.Cycle.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.models.Cycle;
  return proto.models.Cycle.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.models.Cycle} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.models.Cycle}
 */
proto.models.Cycle.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCycleId(value);
      break;
    case 2:
      var value = msg.getCreaturesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readUint32, jspb.BinaryReader.prototype.readMessage, proto.models.Creature.deserializeBinaryFromReader, 0, new proto.models.Creature());
         });
      break;
    case 3:
      var value = new proto.models.Wall;
      reader.readMessage(value,proto.models.Wall.deserializeBinaryFromReader);
      msg.addWalls(value);
      break;
    case 4:
      var value = new proto.models.Step;
      reader.readMessage(value,proto.models.Step.deserializeBinaryFromReader);
      msg.addSteps(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.models.Cycle.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.models.Cycle.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.models.Cycle} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.models.Cycle.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getCreaturesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeUint32, jspb.BinaryWriter.prototype.writeMessage, proto.models.Creature.serializeBinaryToWriter);
  }
  f = message.getWallsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.models.Wall.serializeBinaryToWriter
    );
  }
  f = message.getStepsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.models.Step.serializeBinaryToWriter
    );
  }
};


/**
 * required uint32 cycle_id = 1;
 * @return {number}
 */
proto.models.Cycle.prototype.getCycleId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.models.Cycle} returns this
 */
proto.models.Cycle.prototype.setCycleId = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Cycle} returns this
 */
proto.models.Cycle.prototype.clearCycleId = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Cycle.prototype.hasCycleId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * map<uint32, Creature> creatures = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.models.Creature>}
 */
proto.models.Cycle.prototype.getCreaturesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.models.Creature>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      proto.models.Creature));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.models.Cycle} returns this
 */
proto.models.Cycle.prototype.clearCreaturesMap = function() {
  this.getCreaturesMap().clear();
  return this;};


/**
 * repeated Wall walls = 3;
 * @return {!Array<!proto.models.Wall>}
 */
proto.models.Cycle.prototype.getWallsList = function() {
  return /** @type{!Array<!proto.models.Wall>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.models.Wall, 3));
};


/**
 * @param {!Array<!proto.models.Wall>} value
 * @return {!proto.models.Cycle} returns this
*/
proto.models.Cycle.prototype.setWallsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.models.Wall=} opt_value
 * @param {number=} opt_index
 * @return {!proto.models.Wall}
 */
proto.models.Cycle.prototype.addWalls = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.models.Wall, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.models.Cycle} returns this
 */
proto.models.Cycle.prototype.clearWallsList = function() {
  return this.setWallsList([]);
};


/**
 * repeated Step steps = 4;
 * @return {!Array<!proto.models.Step>}
 */
proto.models.Cycle.prototype.getStepsList = function() {
  return /** @type{!Array<!proto.models.Step>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.models.Step, 4));
};


/**
 * @param {!Array<!proto.models.Step>} value
 * @return {!proto.models.Cycle} returns this
*/
proto.models.Cycle.prototype.setStepsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.models.Step=} opt_value
 * @param {number=} opt_index
 * @return {!proto.models.Step}
 */
proto.models.Cycle.prototype.addSteps = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.models.Step, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.models.Cycle} returns this
 */
proto.models.Cycle.prototype.clearStepsList = function() {
  return this.setStepsList([]);
};


