// source: models.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.models.Neuron');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

goog.forwardDeclare('proto.models.Activation');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.models.Neuron = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.models.Neuron.repeatedFields_, null);
};
goog.inherits(proto.models.Neuron, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.models.Neuron.displayName = 'proto.models.Neuron';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.models.Neuron.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.models.Neuron.prototype.toObject = function(opt_includeInstance) {
  return proto.models.Neuron.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.models.Neuron} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.models.Neuron.toObject = function(includeInstance, msg) {
  var f, obj = {
    activation: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    bias: (f = jspb.Message.getOptionalFloatingPointField(msg, 2)) == null ? undefined : f,
    weightsList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.models.Neuron}
 */
proto.models.Neuron.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.models.Neuron;
  return proto.models.Neuron.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.models.Neuron} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.models.Neuron}
 */
proto.models.Neuron.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.models.Activation} */ (reader.readEnum());
      msg.setActivation(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setBias(value);
      break;
    case 3:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addWeights(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.models.Neuron.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.models.Neuron.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.models.Neuron} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.models.Neuron.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.models.Activation} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getWeightsList();
  if (f.length > 0) {
    writer.writeRepeatedFloat(
      3,
      f
    );
  }
};


/**
 * required Activation activation = 1;
 * @return {!proto.models.Activation}
 */
proto.models.Neuron.prototype.getActivation = function() {
  return /** @type {!proto.models.Activation} */ (jspb.Message.getFieldWithDefault(this, 1, 1));
};


/**
 * @param {!proto.models.Activation} value
 * @return {!proto.models.Neuron} returns this
 */
proto.models.Neuron.prototype.setActivation = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Neuron} returns this
 */
proto.models.Neuron.prototype.clearActivation = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Neuron.prototype.hasActivation = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required float bias = 2;
 * @return {number}
 */
proto.models.Neuron.prototype.getBias = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.models.Neuron} returns this
 */
proto.models.Neuron.prototype.setBias = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Neuron} returns this
 */
proto.models.Neuron.prototype.clearBias = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Neuron.prototype.hasBias = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated float weights = 3;
 * @return {!Array<number>}
 */
proto.models.Neuron.prototype.getWeightsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 3));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.models.Neuron} returns this
 */
proto.models.Neuron.prototype.setWeightsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.models.Neuron} returns this
 */
proto.models.Neuron.prototype.addWeights = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.models.Neuron} returns this
 */
proto.models.Neuron.prototype.clearWeightsList = function() {
  return this.setWeightsList([]);
};


