// source: models.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.models.Traits');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.models.Traits = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.models.Traits.repeatedFields_, null);
};
goog.inherits(proto.models.Traits, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.models.Traits.displayName = 'proto.models.Traits';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.models.Traits.repeatedFields_ = [7,8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.models.Traits.prototype.toObject = function(opt_includeInstance) {
  return proto.models.Traits.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.models.Traits} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.models.Traits.toObject = function(includeInstance, msg) {
  var f, obj = {
    restitution: (f = jspb.Message.getOptionalFloatingPointField(msg, 1)) == null ? undefined : f,
    friction: (f = jspb.Message.getOptionalFloatingPointField(msg, 2)) == null ? undefined : f,
    stamina: (f = jspb.Message.getOptionalFloatingPointField(msg, 3)) == null ? undefined : f,
    blockMass: (f = jspb.Message.getOptionalFloatingPointField(msg, 4)) == null ? undefined : f,
    blockAmount: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
    strength: (f = jspb.Message.getOptionalFloatingPointField(msg, 6)) == null ? undefined : f,
    colorList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 7)) == null ? undefined : f,
    geneCodesList: (f = jspb.Message.getRepeatedField(msg, 8)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.models.Traits}
 */
proto.models.Traits.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.models.Traits;
  return proto.models.Traits.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.models.Traits} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.models.Traits}
 */
proto.models.Traits.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setRestitution(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setFriction(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setStamina(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setBlockMass(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setBlockAmount(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setStrength(value);
      break;
    case 7:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addColor(values[i]);
      }
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.addGeneCodes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.models.Traits.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.models.Traits.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.models.Traits} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.models.Traits.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getColorList();
  if (f.length > 0) {
    writer.writeRepeatedFloat(
      7,
      f
    );
  }
  f = message.getGeneCodesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      8,
      f
    );
  }
};


/**
 * required float restitution = 1;
 * @return {number}
 */
proto.models.Traits.prototype.getRestitution = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.models.Traits} returns this
 */
proto.models.Traits.prototype.setRestitution = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Traits} returns this
 */
proto.models.Traits.prototype.clearRestitution = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Traits.prototype.hasRestitution = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required float friction = 2;
 * @return {number}
 */
proto.models.Traits.prototype.getFriction = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.models.Traits} returns this
 */
proto.models.Traits.prototype.setFriction = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Traits} returns this
 */
proto.models.Traits.prototype.clearFriction = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Traits.prototype.hasFriction = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required float stamina = 3;
 * @return {number}
 */
proto.models.Traits.prototype.getStamina = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.models.Traits} returns this
 */
proto.models.Traits.prototype.setStamina = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Traits} returns this
 */
proto.models.Traits.prototype.clearStamina = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Traits.prototype.hasStamina = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * required float block_mass = 4;
 * @return {number}
 */
proto.models.Traits.prototype.getBlockMass = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.models.Traits} returns this
 */
proto.models.Traits.prototype.setBlockMass = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Traits} returns this
 */
proto.models.Traits.prototype.clearBlockMass = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Traits.prototype.hasBlockMass = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * required uint32 block_amount = 5;
 * @return {number}
 */
proto.models.Traits.prototype.getBlockAmount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.models.Traits} returns this
 */
proto.models.Traits.prototype.setBlockAmount = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Traits} returns this
 */
proto.models.Traits.prototype.clearBlockAmount = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Traits.prototype.hasBlockAmount = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * required float strength = 6;
 * @return {number}
 */
proto.models.Traits.prototype.getStrength = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.models.Traits} returns this
 */
proto.models.Traits.prototype.setStrength = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.models.Traits} returns this
 */
proto.models.Traits.prototype.clearStrength = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.models.Traits.prototype.hasStrength = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated float color = 7;
 * @return {!Array<number>}
 */
proto.models.Traits.prototype.getColorList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 7));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.models.Traits} returns this
 */
proto.models.Traits.prototype.setColorList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.models.Traits} returns this
 */
proto.models.Traits.prototype.addColor = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.models.Traits} returns this
 */
proto.models.Traits.prototype.clearColorList = function() {
  return this.setColorList([]);
};


/**
 * repeated string gene_codes = 8;
 * @return {!Array<string>}
 */
proto.models.Traits.prototype.getGeneCodesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 8));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.models.Traits} returns this
 */
proto.models.Traits.prototype.setGeneCodesList = function(value) {
  return jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.models.Traits} returns this
 */
proto.models.Traits.prototype.addGeneCodes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.models.Traits} returns this
 */
proto.models.Traits.prototype.clearGeneCodesList = function() {
  return this.setGeneCodesList([]);
};


